notifications:
  slack: wtsi-cgpit:ptUMR1tkNyZJYd9TpGoss8WR
  email: false

dist: trusty

language: c

addons:
 apt:
  packages:
   - build-essential
   - autoconf
   - pkg-config
   - check
   - libsubunit-dev

install: true

compiler:
  - gcc

script:
  - ./setup.sh ~/wtsi-opt
